Add xorg-dev and libgl1-mesa-dev packages to be installed by GopherCI.
shurcooL/cmd pull request #6
Opened 2017-05-18 23:05 UTC by bradleyfalzon

dumpglfw3joysticks imports glfw which has these packages as a cgo
dependency. GopherCI can't build the project unless all dependencies
are available. This change instructs GopherCI to install the packages
before the static analysis tools are ran.

See: https://gci.gopherci.io/analysis/479 (analysis of the push to my fork now succeeds)
Fixed by: https://github.com/bradleyfalzon/gopherci/issues/94

2017-05-18 23:28 UTC, dmitshur requested changes
Thanks. It's a bit unfortunate to now have 2 files for CI instead of 1 (or ideally, zero). I hope one day I can replace all of Travis CI with GopherCI, and go back to just one such file.

A few minor change requests, and I can merge this.

2017-05-18 23:28 UTC, shurcooL commented on .gopherci.yml
> +# xorg-dev and libgl1-mesa-dev are cgo dependencies for glfw (imported by dumpglfw3joysticks).
Get rid of the comment, I don't think it's necessary. I prefer to find this information via git blame and the commit message.

2017-05-18 23:28 UTC, shurcooL commented on .gopherci.yml
> +    - libgl1-mesa-dev
Can you swap the order to have them consistent with .travis.yml file, and also use 2 spaces for indent, again for consistency with .travis.yml.

2017-05-18 23:31 UTC, bradleyfalzon commented on .gopherci.yml
> +# xorg-dev and libgl1-mesa-dev are cgo dependencies for glfw (imported by dumpglfw3joysticks).
Agreed.

2017-05-18 23:31 UTC, bradleyfalzon commented on .gopherci.yml
> +    - libgl1-mesa-dev
Done.

2017-05-18 23:33 UTC, bradleyfalzon commented
Yeah, I strongly dislike these dotfiles, and one day in the future I expect the web interface could allow per repo configurations for admins to manage their own projects, but this works better for the general case where people aren't admins but have write access.

2017-05-18 23:44 UTC, shurcooL commented on .gopherci.yml
> +    - libgl1-mesa-dev
What about the 2 space indent?

2017-05-19 00:06 UTC, bradleyfalzon commented on .gopherci.yml
> +    - libgl1-mesa-dev
Apologies, my editor changed it on me.

2017-05-19 00:06 UTC, bradleyfalzon commented on .gopherci.yml
> +    - libgl1-mesa-dev
(that's done now too).

2017-05-19 00:47 UTC, shurcooL commented on .gopherci.yml
> +    - libgl1-mesa-dev
Thanks!

2017-05-19 00:47 UTC, dmitshur approved these changes
LGTM. Thank you!

2017-05-19 00:50 UTC, merged